== Welcome to Enabling RHEL Security for SELinux

= Are You Ready to Elevate Your Red Hat Enterprise Linux Security Skills?

In an era where cyber threats are increasingly sophisticated, securing Red Hat Enterprise Linux (RHEL) systems has never been more critical. In this lab, we'll explore three RHEL native tools that can transform your approach to security and safeguard your digital assets:

. **SELinux** (Security-Enhanced Linux) implements Mandatory Access Control (MAC)

SELinux provides a strong foundation for security, fapolicyd enhances file access control, and Auditd helps monitor system activity for potential threats. Together, they can help ensure the security of your digital assets and protect your infrastructure from cyber attacks.

=== You will learn how to:

Users will leave with practical knowledge on how to install, configure, and manage these security tools, enabling them to apply what they have learned in real-world scenarios.



=== Getting Started

* Follow the Documentation to do this on your own linux machine inside of a VM.

=== How to Follow along with the lab.

* https://github.com/rhpds/showroom-lb1624-rhel-security/blob/main/content/modules/ROOT/pages/index.adoc[Lab 0: Landing Intro Page]
* https://github.com/rhpds/showroom-lb1624-rhel-security/blob/main/content/modules/ROOT/pages/SELinux.adoc[Lab 1: SELinux]
* https://github.com/rhpds/showroom-lb1624-rhel-security/blob/main/content/modules/

=== Speaker Information:

* Joshua Loscar 
** Senior Technical Account Manager, Red Hat



=== Presentation Slides:


