---
site:
  title: "Your Labs Title"
  url: https://github.com/rhpds/showroom_template_zero
  start_page: modules::module-01.adoc

content:
  sources:
    - url: ./
      start_path: content
ui:
  bundle:
    url: https://github.com/rhpds/rhdp_showroom_theme/releases/download/summit-2026/ui-bundle.zip
    snapshot: true

output:
  dir: ./www/www

runtime:
  cache_dir: ./.cache/antora
