---

antora:
  name: modules
  dir: www
  modules:
    - name: module-01
      label: "Introduction"
    - name: module-02
      label: "SELinux"
      solveButton: true
    - name: module-03
      label: "Summary"

tabs:
  - name: ">_ terminal"
    url: /wetty
