---

antora:
  name: modules
  dir: www
  modules:
    - name: module-01
      label: "Step 1"
    - name: module-02
      label: "Step 2"
    - name: module-03
      label: "Step 3"
    - name: module-04
      label: "Step 4"
    - name: module-05
      label: "Step 5"
    - name: module-06
      label: "Step 6"
tabs:
  - name: ">_ terminal"
    url: /wetty
