= Antora

The `antora` key in `ui-config.yml` defines how the documentation site is built using Antora.

[source,yaml]
----
antora:
  name: modules
  dir: www
  modules:
    - name: module-01 
      label: "Writing your lab"
    - name: module-02
      label: "Antora"
    - name: module-03
      label: "Tabs"
----

=== Explanation

- `name`: The name of the documentation folder, here called `modules`.
- `dir`: The directory where the documentation files will be located (`www`). 
- `modules`: The list of modules that make up your lab.

Each module has:

- `name`: The file name within the `pages` directory.
- `label`: A human-readable label for display in navigation.

=== Now lets do it with automation

Red Hat Enterprise Linux System Roles are a collection of supported
Ansible roles that ensure consistent workflows and streamline the
execution of manual tasks.

We have already installed "`rhel-system-roles`" for this lab.

You can check to see what version of `+rhel-system-roles+` package are
installed with the command below. Copy and paste the command below into
*> Shell*.

[source,bash,run]
----
sudo dnf info  rhel-system-roles
----

With our packages installed lets head to the next step.
