= Welcome to Enabling RHEL Security: SELinux

# SELinux 
## Objective

By the end of this guided lab exercise, you will be able to:

1. Understand what SELinux is and its role in system security.
2. Configure basic SELinux settings.
3. Troubleshoot common SELinux issues.
4. Manage SELinux contexts.

## Introduction

SELinux (Security-Enhanced Linux) is a security architecture for Linux systems, providing mechanisms for supporting access control security policies. This lab will
guide you through initial setup and configuration of SELinux, as well as troubleshooting common issues.

Join us on this journey to enhance your RHEL security skills and protect your systems from the ever-evolving landscape of cyber threats.

### Lab Environnement

As part of this lab you will have access to 1 machine:

* rhel

You will have a couple of accounts you will have access to.

* rhel
* root

**Lab Note:** If Using Red Hat Demo System (RHPDS)
The terminal window to your right is already logged into the lab environment as the lab-user user via ssh. All steps of this lab are to be completed as the lab-user user on the bastion server.

When you follow the next steps, you will have instructions then a small box with text that is meant to be used in the terminal.
In the Upper Right Corner there will be a couple of symbols. It Should say something like "BASH", a icon of a clipboard, and an icon of a terminal.

You should also be able to click the terminal icon and the command is then auto typed into the machine terminal.

Alternatively, 

You should be able to click the clipboard icon in the code box to copy the command, and you will either use the middle mouse button or right click and paste. The keyboard shortcuts for copy and paste (ctrl+c and ctrl+v) wont’t work in this.

To Move to the next step, click the "Next" button.

