## Step 2: Verify SELinux Status

**Step 2.1** First, let's check if SELinux is currently enabled on your system. Open a terminal and run the following command:
[source,bash,role="execute",subs=attributes+]
----
sestatus
----

SELinux is enabled by default, so you should see output similar to this:

....
[rhel@rhel ~]$ sestatus
SELinux status:                 enabled
SELinuxfs mount:                /sys/fs/selinux
SELinux root directory:         /etc/selinux
Loaded policy name:             targeted
Current mode:                   enforcing
Mode from config file:          enforcing
Policy MLS status:              enabled
Policy deny_unknown status:     allowed
Memory protection checking:     actual (secure)
Max kernel policy version:      33
[rhel@rhel ~]$
....

The key things here to note are the status (enabled), and the mode (enforcing). Let's look at the configuration next.

SELinux can operate in three modes: Enforcing, Permissive, and Disabled.

- **Enforcing:** Applies the security policy strictly, denying any actions not explicitly allowed by the defined policies. This is the secure mode and is
recommended for production systems.

- **Permissive:** Logs denied operations but does not block them. It's useful for debugging without disrupting system operation.

- **Disabled:** SELinux policies are not enforced, but logs are still active.

**Step 2.2** To change the SELinux mode, use the `setenforce` command:
[source,bash,role="execute",subs=attributes+]
----
cat /etc/selinux/config
----

The important lines here are `SELINUX=enforcing` and `SELINUXTYPE=targeted`. Notice how they line up with the output of `sestatus`?

To move to the next step, click the *Next* button.
